spring.application.name=tailwindaprendizados

# Desativa o cache de templates (Thymeleaf)
spring.thymeleaf.cache=false

# Atualizando a pagina do Google
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729